version: "3.8"

networks: # 自定义网络(默认桥接)
  my_network:
    driver: bridge

services:
  db:
    # 拉取最新的mysql镜像
    image: mysql:latest
    # 设置端口
    ports:
       - "3306:3306"
    environment:
       # 数据库密码
       - MYSQL_ROOT_PASSWORD=QAZwsx1234!
       # 数据库名称
       - MYSQL_DATABASE=music_db
    # 设置挂载目录
    volumes:
       - /home/servers/mysql10/conf:/etc/mysql/conf.d # 挂载配置文件
       - /home/servers/mysql10/data:/var/lib/mysql
       - /home/servers/mysql10/init:/docker-entrypoint-initdb.d/
    # 容器运行发生错误时一直重启
    restart: always
    # 设置网络
    networks:
      - my_network
    
  web:
    # 通过同目录下的Dockerfile构建镜像
    build: ./
    # 容器启动后执行uwsgi启动Django
    command: uwsgi --ini /home/servers/django/uwsgi.ini
    # 设置端口
    ports:
        - "8080:8080"
    volumes:
        - /home/servers/django:/home/servers/django
    # 容器运行发生错误时一直重启
    restart: always
    # 设置网络
    networks:
        - my_network
    depends_on:
        - db

  nginx:
    # 拉取最新的nginx镜像
    image: nginx:latest
    # 设置端口
    ports:
        - "80:80"
    # always表容器运行发生错误时一直重启
    restart: always
    # 设置挂载目录
    volumes:
        - /home/servers/nginx.conf:/etc/nginx/nginx.conf
        - /home/servers/django/music/static/:/home/servers/django/music/static/
    # 设置网络
    networks:
        - my_network
    # 设置容器启动先后顺序
    depends_on:
        - db
        - web