# Generated by Django 5.0 on 2023-12-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('hireDate', models.DateField()),
            ],
            options={
                'verbose_name': '人员信息',
            },
        ),
    ]
